name: OWASP ZAP Scan

on: [push]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZAP
        run: |
          docker pull owasp/zap2docker-stable

      - name: Run ZAP scan
        run: |
          docker run -t owasp/zap2docker-stable zap.sh -cmd -quickurl http://testphp.vulnweb.com/ -quickout report.html -token ${{ secrets.OWASP_ZAP_TOKEN }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report.html
